import Navbar from "@/components/navigation/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/navigation/Footer";
import Sidebar from "@/components/navigation/Sidebar";
import SearchModal from "@/components/modals/SearchModal";
import CartModal from "@/components/modals/CartModal";
import React from "react";
import { ReduxProvider } from "@/redux/provider";
import AppContextProvider from "@/contexts";
import AppThemeprovider from "./AppThemeprovider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "De Kreator Idea",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="relative dark:bg-[#121212] dark:text-[#CCCCCC]">
          <ReduxProvider>
            <AppContextProvider>
              <AppThemeprovider>
                <Sidebar />
                <Navbar />
                <SearchModal />
                <CartModal />
                <div className=" mt-28">{children}</div>
                <Footer />
              </AppThemeprovider>
            </AppContextProvider>
          </ReduxProvider>
        </div>
      </body>
    </html>
  );
}
